title: Ali Mousavi Kherad's College Projects
lang: [en, fa]
description: This is a directory for my college projects.

# ===============================

remote_theme: amkherad-college/texture
#theme: texture

show_excerpts: true

author: Ali Mousavi Kherad

texture:
  title: Ali Mousavi Kherad
  tagline: My college projects directory.
  date_format: "%b %-d, %Y"
  style: blue #[yellow|red|black|blue|green|purple]
  showPicker: false
  showNav: true
  
  navigation:
    - title: My Blog
      url: "https://amkherad.ir"
    - title: Resume
      url: "https://amkherad.i/resume"

  social_links:
    twitter: amkherad
    github:  amkherad
    linkedIn: in/amkherad # format: locale/username

addons:
  - github
  - i18n
  - plugins
  - analytics

sass:
  style: compressed

copyright:
  revision: true

readme_index:
  with_frontmatter: true

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions
  - jekyll-redirect-from


exclude:
  - Makefile
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - requirements.txt
  - node_modules
  - package.json
  - package-lock.json
  - jekyll-rtd-theme.gemspec

whitelist:
  - jekyll-redirect-from
